services:
  # Frontend Service (Streamlit Dashboard)
  - type: web
    name: moving-frontend
    repo: https://github.com/Vel-12/livekit-voice-assistant
    rootDir: .
    runtime: python
    plan: starter
    region: virginia
    
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend.py --server.port=$PORT --server.address=0.0.0.0
    
    envVars:
      - fromGroup: livekit-voice-assistant-env
    
    scaling:
      minInstances: 1
      maxInstances: 2
      targetCPUPercent: 60
      targetMemoryPercent: 60

  # Backend Service (LiveKit Agent)
  - type: worker
    name: moving-backend
    repo: https://github.com/Vel-12/livekit-voice-assistant
    rootDir: .
    runtime: python
    plan: starter
    region: virginia
    
    buildCommand: pip install -r requirements.txt
    startCommand: python agent.py
    
    envVars:
      - fromGroup: livekit-voice-assistant-env
    
    scaling:
      minInstances: 1
      maxInstances: 2
      targetCPUPercent: 60
      targetMemoryPercent: 60

version: "1"